development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI", "mongodb://localhost:27017/upsc_companion_development") %>
  options:
    log_level: :info

test:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI_TEST", "mongodb://localhost:27017/upsc_companion_test") %>
  options:
    log_level: :warn

production:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") %>
  options:
    log_level: :warn
